name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub Pages
        if: github.ref == 'refs/heads/gh-pages'
        run: |
          echo 'www.hendrikboerma.nl' > CNAME

      - name: Set up GitHub Pages for subdomain
        if: github.ref == 'refs/heads/main'
        run: |
          echo 'www.acc.hendrikboerma.nl' > CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
